package CoreLanguage.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.nodeEditor.cellProviders.CellProviderWithRole;
import jetbrains.mps.lang.editor.cellProviders.RefCellCellProvider;
import jetbrains.mps.nodeEditor.EditorManager;
import jetbrains.mps.nodeEditor.InlineCellProvider;
import jetbrains.mps.lang.editor.cellProviders.PropertyCellProvider;
import jetbrains.mps.openapi.editor.style.Style;
import jetbrains.mps.editor.runtime.style.StyleImpl;
import jetbrains.mps.editor.runtime.style.StyleAttributes;
import jetbrains.mps.lang.editor.table.runtime.TableModelFactory;
import jetbrains.mps.lang.editor.table.runtime.TableModel;
import jetbrains.mps.lang.editor.table.runtime.AbstractTableModel;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.editor.table.runtime.EditorCell_Table;
import jetbrains.mps.nodeEditor.cells.ModelAccessor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.nodeEditor.cells.EditorCell_Property;
import jetbrains.mps.openapi.editor.cells.CellActionType;
import jetbrains.mps.editor.runtime.cells.EmptyCellAction;

public class Fact_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_s9jk28_a(editorContext, node);
  }
  private EditorCell createCollection_s9jk28_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_s9jk28_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createConstant_s9jk28_a0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_s9jk28_b0(editorContext, node));
    editorCell.addEditorCell(this.createRefCell_s9jk28_c0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_s9jk28_d0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_s9jk28_e0(editorContext, node));
    editorCell.addEditorCell(this.createTable_s9jk28_f0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_s9jk28_g0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_s9jk28_h0(editorContext, node));
    editorCell.addEditorCell(this.createModelAccess_s9jk28_i0(editorContext, node));
    editorCell.addEditorCell(this.createModelAccess_s9jk28_j0(editorContext, node));
    editorCell.addEditorCell(this.createModelAccess_s9jk28_k0(editorContext, node));
    editorCell.addEditorCell(this.createRefCell_s9jk28_l0(editorContext, node));
    editorCell.addEditorCell(this.createModelAccess_s9jk28_m0(editorContext, node));
    editorCell.addEditorCell(this.createModelAccess_s9jk28_n0(editorContext, node));
    editorCell.addEditorCell(this.createModelAccess_s9jk28_o0(editorContext, node));
    editorCell.addEditorCell(this.createModelAccess_s9jk28_p0(editorContext, node));
    editorCell.addEditorCell(this.createModelAccess_s9jk28_q0(editorContext, node));
    editorCell.addEditorCell(this.createModelAccess_s9jk28_r0(editorContext, node));
    editorCell.addEditorCell(this.createModelAccess_s9jk28_s0(editorContext, node));
    editorCell.addEditorCell(this.createModelAccess_s9jk28_t0(editorContext, node));
    editorCell.addEditorCell(this.createModelAccess_s9jk28_u0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_s9jk28_v0(editorContext, node));
    return editorCell;
  }
  private EditorCell createConstant_s9jk28_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "fact");
    editorCell.setCellId("Constant_s9jk28_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_s9jk28_b0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "from facttype");
    editorCell.setCellId("Constant_s9jk28_b0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefCell_s9jk28_c0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new RefCellCellProvider(node, editorContext);
    provider.setRole("hasFacttype");
    provider.setNoTargetText("<no hasFacttype>");
    EditorCell editorCell;
    provider.setAuxiliaryCellProvider(new Fact_Editor._Inline_s9jk28_a2a());
    editorCell = provider.createEditorCell(editorContext);
    if (editorCell.getRole() == null) {
      editorCell.setReferenceCell(true);
      editorCell.setRole("hasFacttype");
    }
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      EditorManager manager = EditorManager.getInstanceFromContext(editorContext);
      return manager.createNodeRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }
  public static class _Inline_s9jk28_a2a extends InlineCellProvider {
    public _Inline_s9jk28_a2a() {
      super();
    }
    public EditorCell createEditorCell(EditorContext editorContext) {
      return this.createEditorCell(editorContext, this.getSNode());
    }
    public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
      return this.createProperty_s9jk28_a0c0(editorContext, node);
    }
    private EditorCell createProperty_s9jk28_a0c0(EditorContext editorContext, SNode node) {
      CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
      provider.setRole("name");
      provider.setNoTargetText("<no name>");
      provider.setReadOnly(true);
      EditorCell editorCell;
      editorCell = provider.createEditorCell(editorContext);
      editorCell.setCellId("property_name");
      Style style = new StyleImpl();
      CoreLanguageStyles_StyleSheet.apply_Verb(style, editorCell);
      editorCell.getStyle().putAll(style);
      editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
      SNode attributeConcept = provider.getRoleAttribute();
      Class attributeKind = provider.getRoleAttributeClass();
      if (attributeConcept != null) {
        EditorManager manager = EditorManager.getInstanceFromContext(editorContext);
        return manager.createNodeRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
      } else
      return editorCell;
    }
  }
  private EditorCell createConstant_s9jk28_d0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, ":");
    editorCell.setCellId("Constant_s9jk28_d0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.PUNCTUATION_LEFT, 0, true);
    style.set(StyleAttributes.INDENT_LAYOUT_NEW_LINE, 0, true);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_s9jk28_e0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "");
    editorCell.setCellId("Constant_s9jk28_e0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.INDENT_LAYOUT_NEW_LINE, 0, true);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createTable_s9jk28_f0(EditorContext editorContext, SNode node) {
    TableModelFactory creator = new TableModelFactory() {
      public TableModel createTableModel(final SNode node, final EditorContext editorContext) {
        return new AbstractTableModel() {
          @Override
          public int getColumnCount() {
            return ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(node, MetaAdapterFactory.getReferenceLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d40137a4L, "hasFacttype")), MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e05eL, 0x3ed64d29d3f7e429L, "roles"))).count();
          }
          @Override
          public int getRowCount() {
            return 2;
          }
          @Override
          public SNode getValueAt(int row, int column) {
            if (row == 0 && column >= 0) {
              return ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(node, MetaAdapterFactory.getReferenceLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d40137a4L, "hasFacttype")), MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e05eL, 0x3ed64d29d3f7e429L, "roles"))).getElement(column);
            }
            if (row == 1) {
              if (ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d3fbf5e0L, "roles"))).count() > column) {
                return ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d3fbf5e0L, "roles"))).getElement(column);
              }
              SNode variable = SConceptOperations.createNewNode(SNodeOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, "CoreLanguage.structure.ValueOfVariableRoleinFact")));
              SNode value = SConceptOperations.createNewNode(SNodeOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5dbL, "CoreLanguage.structure.IntegerValue")));
              SLinkOperations.setTarget(variable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value"), value);
              ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d3fbf5e0L, "roles"))).addElement(variable);
            }
            return null;
          }
          @Override
          public void createElement(int row, int column) {
            if (row > 0) {
            }
          }
          @Override
          public void insertColumn(int columnNumber) {
          }
          @Override
          public void insertRow(int rowNumber) {
          }
          @Override
          public void deleteColumn(int columnNumber) {
          }
          @Override
          public void deleteRow(int rowNumber) {
          }
        };
      }
    };
    jetbrains.mps.openapi.editor.cells.EditorCell_Collection editorCell = EditorCell_Table.createTable(editorContext, node, creator.createTableModel(node, editorContext), "Table_s9jk28_f0");
    editorCell.setCellId("Table_s9jk28_f0_0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.INDENT_LAYOUT_NEW_LINE, 0, true);
    editorCell.getStyle().putAll(style);
    return editorCell;
  }
  private EditorCell createConstant_s9jk28_g0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "");
    editorCell.setCellId("Constant_s9jk28_g0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.INDENT_LAYOUT_NEW_LINE, 0, true);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_s9jk28_h0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "");
    editorCell.setCellId("Constant_s9jk28_h0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.INDENT_LAYOUT_NEW_LINE, 0, true);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createModelAccess_s9jk28_i0(final EditorContext editorContext, final SNode node) {
    ModelAccessor modelAccessor = new ModelAccessor() {
      public String getText() {
        if (ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(node, MetaAdapterFactory.getReferenceLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d40137a4L, "hasFacttype")), MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e05eL, 0x11a28b573cc30463L, "phrases"))).count() < 1) {
          return "";
        }
        return SPropertyOperations.getString(ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(node, MetaAdapterFactory.getReferenceLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d40137a4L, "hasFacttype")), MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e05eL, 0x11a28b573cc30463L, "phrases"))).getElement(0), MetaAdapterFactory.getProperty(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x11a28b573cc2f879L, 0x11a28b573cc2fcfcL, "phrase"));
      }
      public void setText(String text) {
      }
      public boolean isValidText(String text) {
        return true;
      }
    };
    EditorCell_Property editorCell = EditorCell_Property.create(editorContext, modelAccessor, node);
    editorCell.setAction(CellActionType.DELETE, EmptyCellAction.getInstance());
    editorCell.setAction(CellActionType.BACKSPACE, EmptyCellAction.getInstance());
    editorCell.setCellId("ModelAccess_s9jk28_i0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.INDENT_LAYOUT_NEW_LINE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createModelAccess_s9jk28_j0(final EditorContext editorContext, final SNode node) {
    ModelAccessor modelAccessor = new ModelAccessor() {
      public String getText() {
        if (ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(node, MetaAdapterFactory.getReferenceLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d40137a4L, "hasFacttype")), MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e05eL, 0x3ed64d29d3f7e429L, "roles"))).count() < 1) {
          return "";
        }
        return SPropertyOperations.getString(ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(node, MetaAdapterFactory.getReferenceLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d40137a4L, "hasFacttype")), MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e05eL, 0x3ed64d29d3f7e429L, "roles"))).getElement(0), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
      }
      public void setText(String text) {
      }
      public boolean isValidText(String text) {
        return true;
      }
    };
    EditorCell_Property editorCell = EditorCell_Property.create(editorContext, modelAccessor, node);
    editorCell.setAction(CellActionType.DELETE, EmptyCellAction.getInstance());
    editorCell.setAction(CellActionType.BACKSPACE, EmptyCellAction.getInstance());
    editorCell.setCellId("ModelAccess_s9jk28_j0");
    Style style = new StyleImpl();
    CoreLanguageStyles_StyleSheet.apply_Role(style, editorCell);
    style.set(StyleAttributes.INDENT_LAYOUT_NEW_LINE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createModelAccess_s9jk28_k0(final EditorContext editorContext, final SNode node) {
    ModelAccessor modelAccessor = new ModelAccessor() {
      public String getText() {
        if (ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d3fbf5e0L, "roles"))).count() < 1) {
          return "";
        }
        SNode ValueOfVariable = (SNode) ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d3fbf5e0L, "roles"))).getElement(0);
        if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value")), MetaAdapterFactory.getConcept(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5dbL, "CoreLanguage.structure.IntegerValue"))) {
          SNode value = (SNode) SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value"));
          Integer val = SPropertyOperations.getInteger(value, MetaAdapterFactory.getProperty(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5dbL, 0x3ed64d29d3fbf5dcL, "Value"));
          String s = val.toString();
          return s;
        }
        if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value")), MetaAdapterFactory.getConcept(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0xb3851b217ba9017L, "CoreLanguage.structure.StringValue"))) {
          SNode value = (SNode) SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value"));
          return SPropertyOperations.getString(value, MetaAdapterFactory.getProperty(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0xb3851b217ba9017L, 0xb3851b217ba9018L, "Value"));
        }
        return "";
      }
      public void setText(String text) {
        SNode ValueOfVariable = (SNode) ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d3fbf5e0L, "roles"))).getElement(0);
        if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value")), MetaAdapterFactory.getConcept(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5dbL, "CoreLanguage.structure.IntegerValue"))) {
          SNode value = (SNode) SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value"));
          String s = text;
          Integer val = Integer.valueOf(s);
          SPropertyOperations.set(value, MetaAdapterFactory.getProperty(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5dbL, 0x3ed64d29d3fbf5dcL, "Value"), "" + (val));
        }
        if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value")), MetaAdapterFactory.getConcept(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0xb3851b217ba9017L, "CoreLanguage.structure.StringValue"))) {
          SNode value = (SNode) SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value"));
          SPropertyOperations.set(value, MetaAdapterFactory.getProperty(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0xb3851b217ba9017L, 0xb3851b217ba9018L, "Value"), text);
        }
      }
      public boolean isValidText(String text) {
        return true;
      }
    };
    EditorCell_Property editorCell = EditorCell_Property.create(editorContext, modelAccessor, node);
    editorCell.setAction(CellActionType.DELETE, EmptyCellAction.getInstance());
    editorCell.setAction(CellActionType.BACKSPACE, EmptyCellAction.getInstance());
    editorCell.setCellId("ModelAccess_s9jk28_k0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.INDENT_LAYOUT_NEW_LINE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefCell_s9jk28_l0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new RefCellCellProvider(node, editorContext);
    provider.setRole("hasFacttype");
    provider.setNoTargetText("<no hasFacttype>");
    EditorCell editorCell;
    provider.setAuxiliaryCellProvider(new Fact_Editor._Inline_s9jk28_a11a());
    editorCell = provider.createEditorCell(editorContext);
    if (editorCell.getRole() == null) {
      editorCell.setReferenceCell(true);
      editorCell.setRole("hasFacttype");
    }
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      EditorManager manager = EditorManager.getInstanceFromContext(editorContext);
      return manager.createNodeRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }
  public static class _Inline_s9jk28_a11a extends InlineCellProvider {
    public _Inline_s9jk28_a11a() {
      super();
    }
    public EditorCell createEditorCell(EditorContext editorContext) {
      return this.createEditorCell(editorContext, this.getSNode());
    }
    public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
      return this.createProperty_s9jk28_a0l0(editorContext, node);
    }
    private EditorCell createProperty_s9jk28_a0l0(EditorContext editorContext, SNode node) {
      CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
      provider.setRole("name");
      provider.setNoTargetText("<no name>");
      provider.setReadOnly(true);
      EditorCell editorCell;
      editorCell = provider.createEditorCell(editorContext);
      editorCell.setCellId("property_name_1");
      Style style = new StyleImpl();
      CoreLanguageStyles_StyleSheet.apply_Verb(style, editorCell);
      editorCell.getStyle().putAll(style);
      editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
      SNode attributeConcept = provider.getRoleAttribute();
      Class attributeKind = provider.getRoleAttributeClass();
      if (attributeConcept != null) {
        EditorManager manager = EditorManager.getInstanceFromContext(editorContext);
        return manager.createNodeRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
      } else
      return editorCell;
    }
  }
  private EditorCell createModelAccess_s9jk28_m0(final EditorContext editorContext, final SNode node) {
    ModelAccessor modelAccessor = new ModelAccessor() {
      public String getText() {
        if (ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(node, MetaAdapterFactory.getReferenceLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d40137a4L, "hasFacttype")), MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e05eL, 0x11a28b573cc30463L, "phrases"))).count() < 2) {
          return "";
        }
        return SPropertyOperations.getString(ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(node, MetaAdapterFactory.getReferenceLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d40137a4L, "hasFacttype")), MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e05eL, 0x11a28b573cc30463L, "phrases"))).getElement(1), MetaAdapterFactory.getProperty(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x11a28b573cc2f879L, 0x11a28b573cc2fcfcL, "phrase"));
      }
      public void setText(String text) {
      }
      public boolean isValidText(String text) {
        return true;
      }
    };
    EditorCell_Property editorCell = EditorCell_Property.create(editorContext, modelAccessor, node);
    editorCell.setAction(CellActionType.DELETE, EmptyCellAction.getInstance());
    editorCell.setAction(CellActionType.BACKSPACE, EmptyCellAction.getInstance());
    editorCell.setCellId("ModelAccess_s9jk28_m0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.INDENT_LAYOUT_NEW_LINE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createModelAccess_s9jk28_n0(final EditorContext editorContext, final SNode node) {
    ModelAccessor modelAccessor = new ModelAccessor() {
      public String getText() {
        if (ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(node, MetaAdapterFactory.getReferenceLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d40137a4L, "hasFacttype")), MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e05eL, 0x3ed64d29d3f7e429L, "roles"))).count() < 2) {
          return "";
        }
        return SPropertyOperations.getString(ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(node, MetaAdapterFactory.getReferenceLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d40137a4L, "hasFacttype")), MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e05eL, 0x3ed64d29d3f7e429L, "roles"))).getElement(1), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
      }
      public void setText(String text) {
      }
      public boolean isValidText(String text) {
        return true;
      }
    };
    EditorCell_Property editorCell = EditorCell_Property.create(editorContext, modelAccessor, node);
    editorCell.setAction(CellActionType.DELETE, EmptyCellAction.getInstance());
    editorCell.setAction(CellActionType.BACKSPACE, EmptyCellAction.getInstance());
    editorCell.setCellId("ModelAccess_s9jk28_n0");
    Style style = new StyleImpl();
    CoreLanguageStyles_StyleSheet.apply_Role(style, editorCell);
    style.set(StyleAttributes.INDENT_LAYOUT_NEW_LINE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createModelAccess_s9jk28_o0(final EditorContext editorContext, final SNode node) {
    ModelAccessor modelAccessor = new ModelAccessor() {
      public String getText() {
        if (ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d3fbf5e0L, "roles"))).count() < 2) {
          return "";
        }
        SNode ValueOfVariable = (SNode) ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d3fbf5e0L, "roles"))).getElement(1);
        if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value")), MetaAdapterFactory.getConcept(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5dbL, "CoreLanguage.structure.IntegerValue"))) {
          SNode value = (SNode) SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value"));
          Integer val = SPropertyOperations.getInteger(value, MetaAdapterFactory.getProperty(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5dbL, 0x3ed64d29d3fbf5dcL, "Value"));
          String s = val.toString();
          return s;
        }
        if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value")), MetaAdapterFactory.getConcept(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0xb3851b217ba9017L, "CoreLanguage.structure.StringValue"))) {
          SNode value = (SNode) SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value"));
          return SPropertyOperations.getString(value, MetaAdapterFactory.getProperty(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0xb3851b217ba9017L, 0xb3851b217ba9018L, "Value"));
        }
        return "";
      }
      public void setText(String text) {
        SNode ValueOfVariable = (SNode) ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d3fbf5e0L, "roles"))).getElement(1);
        if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value")), MetaAdapterFactory.getConcept(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5dbL, "CoreLanguage.structure.IntegerValue"))) {
          SNode value = (SNode) SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value"));
          String s = text;
          Integer val = Integer.valueOf(s);
          SPropertyOperations.set(value, MetaAdapterFactory.getProperty(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5dbL, 0x3ed64d29d3fbf5dcL, "Value"), "" + (val));
        }
        if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value")), MetaAdapterFactory.getConcept(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0xb3851b217ba9017L, "CoreLanguage.structure.StringValue"))) {
          SNode value = (SNode) SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value"));
          SPropertyOperations.set(value, MetaAdapterFactory.getProperty(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0xb3851b217ba9017L, 0xb3851b217ba9018L, "Value"), text);
        }
      }
      public boolean isValidText(String text) {
        return true;
      }
    };
    EditorCell_Property editorCell = EditorCell_Property.create(editorContext, modelAccessor, node);
    editorCell.setAction(CellActionType.DELETE, EmptyCellAction.getInstance());
    editorCell.setAction(CellActionType.BACKSPACE, EmptyCellAction.getInstance());
    editorCell.setCellId("ModelAccess_s9jk28_o0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.INDENT_LAYOUT_NEW_LINE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createModelAccess_s9jk28_p0(final EditorContext editorContext, final SNode node) {
    ModelAccessor modelAccessor = new ModelAccessor() {
      public String getText() {
        if (ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(node, MetaAdapterFactory.getReferenceLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d40137a4L, "hasFacttype")), MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e05eL, 0x11a28b573cc30463L, "phrases"))).count() < 3) {
          return "";
        }
        return SPropertyOperations.getString(ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(node, MetaAdapterFactory.getReferenceLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d40137a4L, "hasFacttype")), MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e05eL, 0x11a28b573cc30463L, "phrases"))).getElement(2), MetaAdapterFactory.getProperty(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x11a28b573cc2f879L, 0x11a28b573cc2fcfcL, "phrase"));
      }
      public void setText(String text) {
      }
      public boolean isValidText(String text) {
        return true;
      }
    };
    EditorCell_Property editorCell = EditorCell_Property.create(editorContext, modelAccessor, node);
    editorCell.setAction(CellActionType.DELETE, EmptyCellAction.getInstance());
    editorCell.setAction(CellActionType.BACKSPACE, EmptyCellAction.getInstance());
    editorCell.setCellId("ModelAccess_s9jk28_p0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.INDENT_LAYOUT_NEW_LINE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createModelAccess_s9jk28_q0(final EditorContext editorContext, final SNode node) {
    ModelAccessor modelAccessor = new ModelAccessor() {
      public String getText() {
        if (ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(node, MetaAdapterFactory.getReferenceLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d40137a4L, "hasFacttype")), MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e05eL, 0x3ed64d29d3f7e429L, "roles"))).count() < 3) {
          return "";
        }
        return SPropertyOperations.getString(ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(node, MetaAdapterFactory.getReferenceLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d40137a4L, "hasFacttype")), MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e05eL, 0x3ed64d29d3f7e429L, "roles"))).getElement(2), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
      }
      public void setText(String text) {
      }
      public boolean isValidText(String text) {
        return true;
      }
    };
    EditorCell_Property editorCell = EditorCell_Property.create(editorContext, modelAccessor, node);
    editorCell.setAction(CellActionType.DELETE, EmptyCellAction.getInstance());
    editorCell.setAction(CellActionType.BACKSPACE, EmptyCellAction.getInstance());
    editorCell.setCellId("ModelAccess_s9jk28_q0");
    Style style = new StyleImpl();
    CoreLanguageStyles_StyleSheet.apply_Role(style, editorCell);
    style.set(StyleAttributes.INDENT_LAYOUT_NEW_LINE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createModelAccess_s9jk28_r0(final EditorContext editorContext, final SNode node) {
    ModelAccessor modelAccessor = new ModelAccessor() {
      public String getText() {
        if (ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d3fbf5e0L, "roles"))).count() < 3) {
          return "";
        }
        SNode ValueOfVariable = (SNode) ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d3fbf5e0L, "roles"))).getElement(2);
        if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value")), MetaAdapterFactory.getConcept(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5dbL, "CoreLanguage.structure.IntegerValue"))) {
          SNode value = (SNode) SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value"));
          Integer val = SPropertyOperations.getInteger(value, MetaAdapterFactory.getProperty(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5dbL, 0x3ed64d29d3fbf5dcL, "Value"));
          String s = val.toString();
          return s;
        }
        if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value")), MetaAdapterFactory.getConcept(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0xb3851b217ba9017L, "CoreLanguage.structure.StringValue"))) {
          SNode value = (SNode) SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value"));
          return SPropertyOperations.getString(value, MetaAdapterFactory.getProperty(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0xb3851b217ba9017L, 0xb3851b217ba9018L, "Value"));
        }
        return "";
      }
      public void setText(String text) {
        SNode ValueOfVariable = (SNode) ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d3fbf5e0L, "roles"))).getElement(2);
        if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value")), MetaAdapterFactory.getConcept(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5dbL, "CoreLanguage.structure.IntegerValue"))) {
          SNode value = (SNode) SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value"));
          String s = text;
          Integer val = Integer.valueOf(s);
          SPropertyOperations.set(value, MetaAdapterFactory.getProperty(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5dbL, 0x3ed64d29d3fbf5dcL, "Value"), "" + (val));
        }
        if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value")), MetaAdapterFactory.getConcept(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0xb3851b217ba9017L, "CoreLanguage.structure.StringValue"))) {
          SNode value = (SNode) SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value"));
          SPropertyOperations.set(value, MetaAdapterFactory.getProperty(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0xb3851b217ba9017L, 0xb3851b217ba9018L, "Value"), text);
        }
      }
      public boolean isValidText(String text) {
        return true;
      }
    };
    EditorCell_Property editorCell = EditorCell_Property.create(editorContext, modelAccessor, node);
    editorCell.setAction(CellActionType.DELETE, EmptyCellAction.getInstance());
    editorCell.setAction(CellActionType.BACKSPACE, EmptyCellAction.getInstance());
    editorCell.setCellId("ModelAccess_s9jk28_r0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.INDENT_LAYOUT_NEW_LINE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createModelAccess_s9jk28_s0(final EditorContext editorContext, final SNode node) {
    ModelAccessor modelAccessor = new ModelAccessor() {
      public String getText() {
        if (ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(node, MetaAdapterFactory.getReferenceLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d40137a4L, "hasFacttype")), MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e05eL, 0x11a28b573cc30463L, "phrases"))).count() < 4) {
          return "";
        }
        return SPropertyOperations.getString(ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(node, MetaAdapterFactory.getReferenceLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d40137a4L, "hasFacttype")), MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e05eL, 0x11a28b573cc30463L, "phrases"))).getElement(3), MetaAdapterFactory.getProperty(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x11a28b573cc2f879L, 0x11a28b573cc2fcfcL, "phrase"));
      }
      public void setText(String text) {
      }
      public boolean isValidText(String text) {
        return true;
      }
    };
    EditorCell_Property editorCell = EditorCell_Property.create(editorContext, modelAccessor, node);
    editorCell.setAction(CellActionType.DELETE, EmptyCellAction.getInstance());
    editorCell.setAction(CellActionType.BACKSPACE, EmptyCellAction.getInstance());
    editorCell.setCellId("ModelAccess_s9jk28_s0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.INDENT_LAYOUT_NEW_LINE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createModelAccess_s9jk28_t0(final EditorContext editorContext, final SNode node) {
    ModelAccessor modelAccessor = new ModelAccessor() {
      public String getText() {
        if (ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(node, MetaAdapterFactory.getReferenceLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d40137a4L, "hasFacttype")), MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e05eL, 0x3ed64d29d3f7e429L, "roles"))).count() < 4) {
          return "";
        }
        return SPropertyOperations.getString(ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(node, MetaAdapterFactory.getReferenceLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d40137a4L, "hasFacttype")), MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e05eL, 0x3ed64d29d3f7e429L, "roles"))).getElement(3), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
      }
      public void setText(String text) {
      }
      public boolean isValidText(String text) {
        return true;
      }
    };
    EditorCell_Property editorCell = EditorCell_Property.create(editorContext, modelAccessor, node);
    editorCell.setAction(CellActionType.DELETE, EmptyCellAction.getInstance());
    editorCell.setAction(CellActionType.BACKSPACE, EmptyCellAction.getInstance());
    editorCell.setCellId("ModelAccess_s9jk28_t0");
    Style style = new StyleImpl();
    CoreLanguageStyles_StyleSheet.apply_Role(style, editorCell);
    style.set(StyleAttributes.INDENT_LAYOUT_NEW_LINE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createModelAccess_s9jk28_u0(final EditorContext editorContext, final SNode node) {
    ModelAccessor modelAccessor = new ModelAccessor() {
      public String getText() {
        if (ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d3fbf5e0L, "roles"))).count() < 4) {
          return "";
        }
        SNode ValueOfVariable = (SNode) ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d3fbf5e0L, "roles"))).getElement(3);
        if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value")), MetaAdapterFactory.getConcept(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5dbL, "CoreLanguage.structure.IntegerValue"))) {
          SNode value = (SNode) SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value"));
          Integer val = SPropertyOperations.getInteger(value, MetaAdapterFactory.getProperty(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5dbL, 0x3ed64d29d3fbf5dcL, "Value"));
          String s = val.toString();
          return s;
        }
        if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value")), MetaAdapterFactory.getConcept(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0xb3851b217ba9017L, "CoreLanguage.structure.StringValue"))) {
          SNode value = (SNode) SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value"));
          return SPropertyOperations.getString(value, MetaAdapterFactory.getProperty(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0xb3851b217ba9017L, 0xb3851b217ba9018L, "Value"));
        }
        return "";
      }
      public void setText(String text) {
        SNode ValueOfVariable = (SNode) ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3f7e063L, 0x3ed64d29d3fbf5e0L, "roles"))).getElement(3);
        if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value")), MetaAdapterFactory.getConcept(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5dbL, "CoreLanguage.structure.IntegerValue"))) {
          SNode value = (SNode) SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value"));
          String s = text;
          Integer val = Integer.valueOf(s);
          SPropertyOperations.set(value, MetaAdapterFactory.getProperty(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5dbL, 0x3ed64d29d3fbf5dcL, "Value"), "" + (val));
        }
        if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value")), MetaAdapterFactory.getConcept(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0xb3851b217ba9017L, "CoreLanguage.structure.StringValue"))) {
          SNode value = (SNode) SLinkOperations.getTarget(ValueOfVariable, MetaAdapterFactory.getContainmentLink(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0x3ed64d29d3fbf5e2L, 0x3ed64d29d3fbf5e7L, "value"));
          SPropertyOperations.set(value, MetaAdapterFactory.getProperty(0xff306b76056a4ed1L, 0xb5c4df8d840614d7L, 0xb3851b217ba9017L, 0xb3851b217ba9018L, "Value"), text);
        }
      }
      public boolean isValidText(String text) {
        return true;
      }
    };
    EditorCell_Property editorCell = EditorCell_Property.create(editorContext, modelAccessor, node);
    editorCell.setAction(CellActionType.DELETE, EmptyCellAction.getInstance());
    editorCell.setAction(CellActionType.BACKSPACE, EmptyCellAction.getInstance());
    editorCell.setCellId("ModelAccess_s9jk28_u0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.INDENT_LAYOUT_NEW_LINE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_s9jk28_v0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "");
    editorCell.setCellId("Constant_s9jk28_v0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.INDENT_LAYOUT_ON_NEW_LINE, 0, true);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
}
