package CoreLanguage.behavior;

/*Generated by MPS */


public abstract class AbstractValue_BehaviorDescriptor extends Concept_BehaviorDescriptor {
  public AbstractValue_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "CoreLanguage.structure.AbstractValue";
  }
}
