package CoreLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }
  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 0:
        return new Concept_BehaviorDescriptor();
      case 6:
        return new Objecttype_BehaviorDescriptor();
      case 3:
        return new Facttype_BehaviorDescriptor();
      case 2:
        return new Fact_BehaviorDescriptor();
      case 14:
        return new Variable_BehaviorDescriptor();
      case 5:
        return new IntegerValue_BehaviorDescriptor();
      case 13:
        return new ValueOfVariableRoleinFact_BehaviorDescriptor();
      case 1:
        return new Context_BehaviorDescriptor();
      case 18:
        return new VariableRole_BehaviorDescriptor();
      case 17:
        return new VariableReferenceRole_BehaviorDescriptor();
      case 8:
        return new ObjecttypeRole_BehaviorDescriptor();
      case 7:
        return new ObjecttypeReferenceRole_BehaviorDescriptor();
      case 10:
        return new Proposition_BehaviorDescriptor();
      case 9:
        return new Phrase_BehaviorDescriptor();
      case 4:
        return new IntegerType_BehaviorDescriptor();
      case 11:
        return new StringType_BehaviorDescriptor();
      case 12:
        return new StringValue_BehaviorDescriptor();
      case 16:
        return new VariableReference_BehaviorDescriptor();
      case 15:
        return new VariableChild_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }
  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"CoreLanguage.structure.Concept", "CoreLanguage.structure.Context", "CoreLanguage.structure.Fact", "CoreLanguage.structure.Facttype", "CoreLanguage.structure.IntegerType", "CoreLanguage.structure.IntegerValue", "CoreLanguage.structure.Objecttype", "CoreLanguage.structure.ObjecttypeReferenceRole", "CoreLanguage.structure.ObjecttypeRole", "CoreLanguage.structure.Phrase", "CoreLanguage.structure.Proposition", "CoreLanguage.structure.StringType", "CoreLanguage.structure.StringValue", "CoreLanguage.structure.ValueOfVariableRoleinFact", "CoreLanguage.structure.Variable", "CoreLanguage.structure.VariableChild", "CoreLanguage.structure.VariableReference", "CoreLanguage.structure.VariableReferenceRole", "CoreLanguage.structure.VariableRole"};
}
