package CoreLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Concept_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Concept_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "CoreLanguage.structure.Concept";
  }
}
