package CoreLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Context_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Context_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "CoreLanguage.structure.Context";
  }
}
