package CoreLanguage.behavior;

/*Generated by MPS */


public class Fact_BehaviorDescriptor extends Concept_BehaviorDescriptor {
  public Fact_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "CoreLanguage.structure.Fact";
  }
}
