package CoreLanguage.behavior;

/*Generated by MPS */


public abstract class IdentifyingVariable_BehaviorDescriptor extends Concept_BehaviorDescriptor {
  public IdentifyingVariable_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "CoreLanguage.structure.IdentifyingVariable";
  }
}
