package CoreLanguage.behavior;

/*Generated by MPS */


public class IntegerType_BehaviorDescriptor extends VariableType_BehaviorDescriptor {
  public IntegerType_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "CoreLanguage.structure.IntegerType";
  }
}
