package CoreLanguage.behavior;

/*Generated by MPS */


public class IntegerValue_BehaviorDescriptor extends AbstractValue_BehaviorDescriptor {
  public IntegerValue_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "CoreLanguage.structure.IntegerValue";
  }
}
