package CoreLanguage.behavior;

/*Generated by MPS */


public class ObjecttypeRole_BehaviorDescriptor extends ObjecttypeRoleinFacttype_BehaviorDescriptor {
  public ObjecttypeRole_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "CoreLanguage.structure.ObjecttypeRole";
  }
}
