package CoreLanguage.behavior;

/*Generated by MPS */


public class ObjecttypeReferenceRole_BehaviorDescriptor extends ObjecttypeRoleinFacttype_BehaviorDescriptor {
  public ObjecttypeReferenceRole_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "CoreLanguage.structure.ObjecttypeReferenceRole";
  }
}
