package CoreLanguage.behavior;

/*Generated by MPS */


public abstract class ObjecttypeRoleinFacttype_BehaviorDescriptor extends RoleinFacttype_BehaviorDescriptor {
  public ObjecttypeRoleinFacttype_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "CoreLanguage.structure.ObjecttypeRoleinFacttype";
  }
}
