package CoreLanguage.behavior;

/*Generated by MPS */


public abstract class RoleinFact_BehaviorDescriptor extends Concept_BehaviorDescriptor {
  public RoleinFact_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "CoreLanguage.structure.RoleinFact";
  }
}
