package CoreLanguage.behavior;

/*Generated by MPS */


public class StringType_BehaviorDescriptor extends VariableType_BehaviorDescriptor {
  public StringType_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "CoreLanguage.structure.StringType";
  }
}
