package CoreLanguage.behavior;

/*Generated by MPS */


public class StringValue_BehaviorDescriptor extends AbstractValue_BehaviorDescriptor {
  public StringValue_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "CoreLanguage.structure.StringValue";
  }
}
