package CoreLanguage.behavior;

/*Generated by MPS */


public class ValueOfVariableRoleinFact_BehaviorDescriptor extends RoleinFact_BehaviorDescriptor {
  public ValueOfVariableRoleinFact_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "CoreLanguage.structure.ValueOfVariableRoleinFact";
  }
}
