package CoreLanguage.behavior;

/*Generated by MPS */


public class VariableChild_BehaviorDescriptor extends IdentifyingVariable_BehaviorDescriptor {
  public VariableChild_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "CoreLanguage.structure.VariableChild";
  }
}
