package CoreLanguage.behavior;

/*Generated by MPS */


public class VariableRole_BehaviorDescriptor extends VariableRoleinFacttype_BehaviorDescriptor {
  public VariableRole_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "CoreLanguage.structure.VariableRole";
  }
}
