package CoreLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class VariableType_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public VariableType_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "CoreLanguage.structure.VariableType";
  }
}
