package CoreLanguage.behavior;

/*Generated by MPS */


public class VariableReference_BehaviorDescriptor extends IdentifyingVariable_BehaviorDescriptor {
  public VariableReference_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "CoreLanguage.structure.VariableReference";
  }
}
