package CoreLanguage.behavior;

/*Generated by MPS */


public class VariableReferenceRole_BehaviorDescriptor extends VariableRoleinFacttype_BehaviorDescriptor {
  public VariableReferenceRole_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "CoreLanguage.structure.VariableReferenceRole";
  }
}
