package CoreLanguage.behavior;

/*Generated by MPS */


public abstract class VariableRoleinFacttype_BehaviorDescriptor extends RoleinFacttype_BehaviorDescriptor {
  public VariableRoleinFacttype_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "CoreLanguage.structure.VariableRoleinFacttype";
  }
}
